pid=\$(cat node_services/python_pid_net_maintenance.file)
kill -SIGINT \$pid
echo python process \$pid stopping...
pid=\$(cat node_services/python_pid_chat.file)
kill -SIGINT \$pid
echo python process \$pid stopping...
pid=\$(cat node_services/python_pid_net_storage.file)
kill -SIGINT \$pid
echo python process \$pid stopping...
pid=\$(cat node_services/python_pid_PoH.file)
kill -SIGINT \$pid
echo python process \$pid stopping...
